// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Order struct {
	ID         pgtype.UUID      `json:"id"`
	CustomerID pgtype.UUID      `json:"customer_id"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type OrderItem struct {
	ID           pgtype.UUID `json:"id"`
	OrderID      pgtype.UUID `json:"order_id"`
	ProductID    pgtype.UUID `json:"product_id"`
	Quantity     int32       `json:"quantity"`
	PriceInCents int32       `json:"price_in_cents"`
}

type Product struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	PriceInCents int32            `json:"price_in_cents"`
	Quantity     int32            `json:"quantity"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	CategoryID   pgtype.UUID      `json:"category_id"`
}
