// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	FindOrderById(ctx context.Context, id pgtype.UUID) (Order, error)
	FindProductById(ctx context.Context, id pgtype.UUID) (Product, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
